name: hawkeye
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  r_dart_library:
    git:
      url: 'https://github.com/YK-Unit/r_dart_library.git'
      ref: 0.2.1
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  screen_utils: ^0.0.1
  flutter_screenutil: ^5.0.0
  contacts_service: ^0.6.1
  permission_handler: ^7.0.0
  http: ^0.13.1
  get_storage: ^2.0.2
  modal_progress_hud: ^0.1.3
  flutter_spinkit: ^5.0.0
  jwt_decoder: ^2.0.1
  geolocator: ^7.0.3
  url_launcher: ^6.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/images/app_icon.png
flutter:
  uses-material-design: true
  fonts:
  - family: Nunito
    fonts:
    - asset: assets/fonts/Nunito/Nunito-Black.ttf
    - asset: assets/fonts/Nunito/Nunito-BlackItalic.ttf
    - asset: assets/fonts/Nunito/Nunito-Bold.ttf
    - asset: assets/fonts/Nunito/Nunito-BoldItalic.ttf
    - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
    - asset: assets/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
    - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
    - asset: assets/fonts/Nunito/Nunito-ExtraLightItalic.ttf
    - asset: assets/fonts/Nunito/Nunito-Italic.ttf
    - asset: assets/fonts/Nunito/Nunito-Light.ttf
    - asset: assets/fonts/Nunito/Nunito-LightItalic.ttf
    - asset: assets/fonts/Nunito/Nunito-Regular.ttf
    - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
    - asset: assets/fonts/Nunito/Nunito-SemiBoldItalic.ttf
  assets:
  - assets/images/HAWK-EYE__2_-removebg-preview.png
  - assets/images/HAWK-EYE_logo.png
  - assets/images/app_icon.png
flr:
  core_version: 3.1.0
  dartfmt_line_length: 80
  assets:
  - assets/images/
  fonts:
  - assets/fonts/
